### PR TITLE
Symphony 2.2 compatibility fix and romanian translation

### PR DESCRIPTION
**Pull request by vlad-ghita**
Fixed new accessor.

Added romanian translation.

Please review the fix and integrate it pls. Don't know of any other bugs, it works fine, so far.

Thanks.

Btw: nice extension   ! bd !.

### CODE REVIEW

**Comment by klaftertief** [comment]
Thanks. I'm planning to release a new Version today or tomorrow, I'll merge your changes then.

**Comment by vlad-ghita** [comment]
Btw, I found the usage of "$this->_engine" several times in "field.imagecropper.php".

According to the Symphony Blog it should be replaced with "Symphony::Engine()". When updating, please check those accessors as well.

**Comment by klaftertief** [comment]
Will do. Thanks.

**Comment by klaftertief** [comment]
Merged.

**Pull request closed without merging**
