### PR TITLE
Added compatibility with "Image Upload" field

### PR DESCRIPTION
**Pull request by vlad-ghita**
For this to work with `Field: Image upload`.

Thanks, Vlad

### CODE REVIEW

**Comment by madaerodog** [comment]
cool, thank you for that, now if only it would all work with Symphony 2.25 ... but for that the modified JIT would have to be updated

**Comment by vlad-ghita** [comment]
Well, it does work with Symphony 2.2.5. I'm using it daily, including the modified JIT (it's [v1.10 for jCrop](https://github.com/klaftertief/jit_image_manipulation/tree/jCrop))

**Comment by madaerodog** [comment]
then how come I am getting this error ?  Fatal error: Undefined class constant 'kERROR' in /extensions/jit_image_manipulation/lib/image.php on line 85

Thanks in advance, if you have any hints for me

**Comment by vlad-ghita** [comment]
Are you sure you have [this](https://github.com/klaftertief/jit_image_manipulation/tree/jCrop) version of the extension?

**Comment by madaerodog** [comment]
hmm I was using the master version of that https://github.com/klaftertief/jit_image_manipulation and that is 1.06, you are right, thanks man!

**Comment by klaftertief** [comment]
Didn't merge it directly, but added a `$supported_upload_fields` array. Thanks.

**Pull request closed without merging**
